language: python

addons:
    apt:
        packages:
            # http://superuser.com/a/1057144/34733
            - oracle-java8-installer
            - xmlstarlet

python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"

env:
    - REQUIRES=minimum
    - REQUIRES=normal

install:
    - if [ "$TRAVIS_PYTHON_VERSION" = pypy ]; then . `tools/pypy_env.sh`; fi
    - if [ "$REQUIRES" = minimum ]; then tools/minimum_requires.sh; fi
    - pip install -e .
    - pip install -r tools/requirements.txt
    - tools/vnu.sh install
    - tools/jshint.sh install

cache: pip

script:
    # Basic stuff.
    - python setup.py check --strict --restructuredtext
    - tools/pylint_all.sh -j 2
    - py.test

    # Build the files to be uploaded to pythonhosted.org.
    - tools/build_extra_doc.sh

    # Validate HTML-related stuff.
    # This includes validating an actual HTML report (``showcase.html``).
    - tools/vnu.sh run extra_doc/_build/*.html
    - tools/css_validator.sh httpolice/reports/html.css
    - tools/jshint.sh run httpolice/reports/html.js

    # Although the main docs (``doc/``) are processed by Read the Docs,
    # we still want to check that they are building OK.
    # But first, make sure that the included API example works.
    - python doc/api_example.py && grep -q 1194 report.html
    - sphinx-build -W doc/ doc/_build/

    # Check that the source distribution includes everything it should,
    # and nothing it shouldn't (including all the files we just built).
    - check-manifest

deploy:
    on:
        tags: true
        # Only release from one of the environments.
        python: "3.5"
        condition: $REQUIRES = normal
    provider: pypi
    user: vfaronov
    password:
        secure: dlLrrEWu99XENO7U7qubqogu/RlSKsxcmWE2mIdz8e+w0RKzv8ahDjohEarwI06a4oX8rQYm6azTnNt+yeY0dL9fjucuFbIvJ1Tui2SLjhYgD6BeFAL2sGalJikVBalWy6j2cK9kaun2zY0jhLT+Y+auMOlJAOohcdfq6o8W+5dDLPo+SZElI1vNrgPWwsm1ENBWFuzQF3j/sjRzpqJhhZlWmZdwrWaYysNDT4Saflu9By1jLk4yDTyqsGHtRXqe4bc5vfVFXXE3FthEB86ry89jMHnjmYodUyJktDBFfOqodj2OOzKhxv1R3oVkUhUufiOVa5Ji7tR9D2F5gll/g8R1K59ifRpiCEbQVrk+320M/HPBjpcWuILCkm3OTE56M2Ncft+NpQ+A9escyU+A64YR/PYFMRWAfRwAxUZUVD/YDXh8Ar+pRygPnorINXrFcceEcClwxX9VYcYX0PBRbmNafpXkW/t05m3Nh50jD3+y17BeKBTAvzmosj1TuJ88TRlpTBocF6CkUIv9lIuJ9c0l0gh5aJR6CBWv8jMuKDDpAYPaBEbU9SZvyQvBva0nx/v/lncO6epLefhoYfCh/DDYRLucr+zy3ChmCd/BeJRo3gw/piZOqWmWU4H48DRrrkEJXC4dSSgEuNElq/GgZ1lK3X1zWjYCSNGDTpNqH5Q=
    # Also upload files to pythonhosted.org.
    skip_cleanup: true
    docs_dir: extra_doc/_build
