language: python

addons:
    apt:
        packages:
            # http://superuser.com/a/1057144/34733
            - oracle-java8-installer
            - xmlstarlet

python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"

env:
    - REQUIRES=minimum
    - REQUIRES=normal

install:
    - if [ "$TRAVIS_PYTHON_VERSION" = pypy ]; then . `tools/pypy_env.sh`; fi
    - if [ "$REQUIRES" = minimum ]; then tools/minimum_requires.sh; fi
    - pip install -e .
    - pip install -r tools/requirements.txt
    - tools/vnu.sh install
    - tools/jshint.sh install

cache: pip

script:
    - python setup.py check --strict --restructuredtext
    - tools/pylint_all.sh -j 2
    - py.test
    - tools/build_extra_doc.sh

    # This also validates an actual HTML report (``showcase.html``).
    - tools/vnu.sh run extra_doc/_build/*.html

    - tools/css_validator.sh httpolice/reports/html.css
    - tools/jshint.sh run httpolice/reports/html.js

    # Check that the API example works.
    - python doc/api_example.py && grep -q 1194 report.html

    - sphinx-build -W doc/ doc/_build/
    - check-manifest
    - python setup.py sdist bdist_wheel
